# Generated by Django 4.2.6 on 2023-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='c',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
