# Generated by Django 4.2.6 on 2023-10-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0003_alter_mmc_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmc',
            name='c',
            field=models.FloatField(),
        ),
    ]
