# Generated by Django 4.2.6 on 2023-11-05 21:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0004_alter_mmc_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='k',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='p_k',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
