# Generated by Django 4.2.6 on 2023-10-26 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0004_alter_mmc_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='P_0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mmc',
            name='P_k',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='k',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='mu_k',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='rho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mmc',
            name='c',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mmc',
            name='mu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mmc',
            name='myLambda',
            field=models.FloatField(default=0),
        ),
    ]
