# Generated by Django 4.2.6 on 2023-11-06 01:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0005_mmc_k_mmc_p_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='l_q',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='l_s',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='l_x',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='mu_k',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='p_0',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='p_queue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='rho',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='w_q',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='w_s',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
