# Generated by Django 4.2.6 on 2023-11-23 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0006_mmc_l_q_mmc_l_s_mmc_l_x_mmc_mu_k_mmc_p_0_mmc_p_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='w_s_graph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
