# Generated by Django 4.2.6 on 2023-10-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0006_alter_mmc_p_0_alter_mmc_p_k_alter_mmc_c_alter_mmc_k_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmc',
            name='P_0',
        ),
        migrations.RemoveField(
            model_name='mmc',
            name='P_k',
        ),
        migrations.RemoveField(
            model_name='mmc',
            name='k',
        ),
        migrations.RemoveField(
            model_name='mmc',
            name='mu_k',
        ),
        migrations.RemoveField(
            model_name='mmc',
            name='rho',
        ),
    ]
