# Generated by Django 4.2.6 on 2024-01-01 04:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0007_mmc_w_s_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmc',
            name='packagesInQueue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmc',
            name='queueEventTimes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
